### PR TITLE
Add syntax hi-lighting to Readme code.

### PR DESCRIPTION
**Pull request by ryngonzalez**
Just thought it would be easier to read.

### CODE REVIEW

**Comment by ralyodio** [comment]
Thanks for the patch, is there anyway to look at this? I cloned your fork, but I don't see the changes.

**Comment by ryngonzalez** [comment]
The changes are only visible when the markdown file is displayed on GitHub—you should be able to see the highlighting on the repo's page now.

**Comment by ralyodio** [comment]
ok, its breaking my local markdown reader. probably because this is a github flavored md feature. Do you know if this is supported on NPM? I'm hesitant to add it if it only works on github.

**Comment by ryngonzalez** [comment]
NPM uses GitHub-Flavored-Markdown.

**Comment by ralyodio** [comment]
ok, thanks. just pushed a new version. https://www.npmjs.com/package/app-notify

**Pull request merged**
